name: "Docker Image"
description: "Retrieve a docker images filename"

inputs:
  PROJECT_ID:
    required: true
    description: "gcp project target for the container"
  SERVICE_NAME:
    required: true
    description: "the name provided to the docker container"
  DOCKER_TAG:
    required: true
    description: "the tag provided for the docker container"
outputs:
  DOCKER_IMAGE_ENC:
    description: "The docker image url - base64 encoded"
    value: ${{steps.encode.outputs.tagged_image_enc}}

runs:
  using: "composite"
  steps:
    
    - name: Prepare
      shell: bash
      id: prepare
      run: |
        TAG=${{ inputs.DOCKER_TAG }}
        IMAGE="eu.gcr.io/${{ inputs.PROJECT_ID }}/${{ inputs.SERVICE_NAME }}"
        echo "tagged_image=${IMAGE}:${TAG}" >> $GITHUB_OUTPUT
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
    
    - name: Encode
      shell: bash
      id: encode
      run: |
        echo "tagged_image_enc=$(echo -n '${{steps.prepare.outputs.tagged_image}}' | base64 -w0 | base64 -w0 )" >> $GITHUB_OUTPUT
