name: "SonarCloud"
description: "Use SonarCloud to get insight into code quality"
inputs:
  NPM_REGISTRY_TOKEN:
    required: true
    description: "Your personal access token - PAT"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
      env:
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - run: npm ci
        npm run lint
        npm test
      shell: bash
      env:
        CI: "true"
        NPM_TOKEN: ${{ inputs.NPM_REGISTRY_TOKEN }}
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}